name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test Actions
        uses: rara-tan/gh-actions-ts-template@v0.1
        with:
          name: "Tom"

